services:
  comfy-toolkit:
    container_name: comfy-toolkit
    image: comfy-toolkit:latest
    volumes:
      - ${COMFY_CORE_PATH}:/usr/src/comfy
      - ${COMFY_TORRENTS_PATH}:/usr/src/torrents
      - G:\bcs:/usr/src/torrents/bcs
      - ${COMFY_DATA_PATH}:/usr/src/data
    environment:
      COMFY_TMPFS_SIZE: "${COMFY_TMPFS_SIZE}"
    build:
      context: ./
      dockerfile: .docker/images/comfy-toolkit/Dockerfile
    tty: yes
    env_file:
    - .env
    privileged: true