services:
  nyananime-toolkit:
    container_name: nyananime-toolkit
    image: nyananime-toolkit:latest
    volumes:
      - ${NYANANIME_CORE_PATH}:/usr/src/nyananime
      - ${NYANANIME_TORRENTS_PATH}:/usr/src/torrents
      - ${NYANANIME_DATA_PATH}:/usr/src/data
    environment:
      NYANANIME_TMPFS_SIZE: "${NYANANIME_TMPFS_SIZE}"
    build:
      context: ./
      dockerfile: .docker/images/nyananime-toolkit/Dockerfile
    tty: yes
    env_file:
    - .env